# Generated by Django 5.0 on 2023-12-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_desk_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='username',
            field=models.CharField(default='efsf', max_length=50),
            preserve_default=False,
        ),
    ]
