# Generated by Django 5.0 on 2023-12-29 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_desk_api', '0003_project_contributor_age_contributor_can_be_contacted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='username',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(default=2146, on_delete=django.db.models.deletion.CASCADE, related_name='authored_projects', to='soft_desk_api.contributor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='projects', to='soft_desk_api.contributor'),
        ),
    ]
